// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pointly.Data;

#nullable disable

namespace pointlyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410062903_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Pointly.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPointsPool")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Pointly.Models.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailablePoints")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByAdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Chargers");
                });

            modelBuilder.Entity("Pointly.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Pointly.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChargedByChargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChrargedByChargerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChrargedByChargerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("Pointly.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointsCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuantityAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Pointly.Models.PointAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromChargerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToChargerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToMerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromAdminId");

                    b.HasIndex("FromChargerId");

                    b.HasIndex("ToChargerId");

                    b.HasIndex("ToMerchantId");

                    b.ToTable("PointAssignments");
                });

            modelBuilder.Entity("Pointly.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Pointly.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OfferId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PointsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OfferId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Pointly.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pointly.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Pointly.Models.Admin", b =>
                {
                    b.HasOne("Pointly.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Pointly.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pointly.Models.Charger", b =>
                {
                    b.HasOne("Pointly.Models.Admin", "AssignedByAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedByAdminId");

                    b.HasOne("Pointly.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Pointly.Models.Charger", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pointly.Models.Customer", b =>
                {
                    b.HasOne("Pointly.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Pointly.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pointly.Models.Merchant", b =>
                {
                    b.HasOne("Pointly.Models.Charger", "ChrargedByCharger")
                        .WithMany()
                        .HasForeignKey("ChrargedByChargerId");

                    b.HasOne("Pointly.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Pointly.Models.Merchant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChrargedByCharger");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pointly.Models.Offer", b =>
                {
                    b.HasOne("Pointly.Models.Merchant", "Merchant")
                        .WithMany("Offers")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Pointly.Models.PointAssignment", b =>
                {
                    b.HasOne("Pointly.Models.Admin", "FromAdmin")
                        .WithMany()
                        .HasForeignKey("FromAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pointly.Models.Charger", "FromCharger")
                        .WithMany()
                        .HasForeignKey("FromChargerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pointly.Models.Charger", "ToCharger")
                        .WithMany("PointAssignments")
                        .HasForeignKey("ToChargerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pointly.Models.Merchant", "ToMerchant")
                        .WithMany()
                        .HasForeignKey("ToMerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromAdmin");

                    b.Navigation("FromCharger");

                    b.Navigation("ToCharger");

                    b.Navigation("ToMerchant");
                });

            modelBuilder.Entity("Pointly.Models.Store", b =>
                {
                    b.HasOne("Pointly.Models.Merchant", "Merchant")
                        .WithMany("Stores")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Pointly.Models.Transaction", b =>
                {
                    b.HasOne("Pointly.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pointly.Models.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pointly.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId");

                    b.Navigation("Customer");

                    b.Navigation("Merchant");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Pointly.Models.Wallet", b =>
                {
                    b.HasOne("Pointly.Models.Customer", "Customer")
                        .WithOne("Wallet")
                        .HasForeignKey("Pointly.Models.Wallet", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pointly.Models.Charger", b =>
                {
                    b.Navigation("PointAssignments");
                });

            modelBuilder.Entity("Pointly.Models.Customer", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Pointly.Models.Merchant", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
